[versions]
dagger = "2.56.2"
jetbrainsKotlinJvm = "2.1.20"

[libraries]
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }

[plugins]
anvil = { id = "dev.zacsweers.anvil", version = "0.4.1" }
ksp = { id = "com.google.devtools.ksp", version = "2.1.20-2.0.0" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
